const dbSchema = `
 vendor table schema (name: vendor_vendormodel) -> [
  {
    column_name: "id",
    data_type: "bigint",
    is_nullable: "NO",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 64,
    numeric_scale: 0,
  }, {
    column_name: "image",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 100,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "store_name",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "person_name",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "description",
    data_type: "text",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "address_line",
    data_type: "text",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "business_email",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 254,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "business_address",
    data_type: "text",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "landmark",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 254,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "city",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "state",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "company_type",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "status",
    data_type: "character varying",
    is_nullable: "NO",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "latitude",
    data_type: "double precision",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 53,
    numeric_scale: null,
  }, {
    column_name: "longitude",
    data_type: "double precision",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 53,
    numeric_scale: null,
  }, {
    column_name: "contact_phone",
    data_type: "bigint",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 64,
    numeric_scale: 0,
  }, {
    column_name: "tabs_status",
    data_type: "jsonb",
    is_nullable: "NO",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "master_profile_id_id",
    data_type: "bigint",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 64,
    numeric_scale: 0,
  }, {
    column_name: "online",
    data_type: "boolean",
    is_nullable: "NO",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "vendor_group_id_id",
    data_type: "bigint",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 64,
    numeric_scale: 0,
  }, {
    column_name: "vendor_rating",
    data_type: "double precision",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: 53,
    numeric_scale: null,
  }, {
    column_name: "fssai_number",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 254,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "avg_preparing_time",
    data_type: "time without time zone",
    is_nullable: "NO",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "placeId",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 256,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "shorturl",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 254,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "recent_activity",
    data_type: "timestamp with time zone",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: null,
    numeric_precision: null,
    numeric_scale: null,
  }, {
    column_name: "trade_name",
    data_type: "character varying",
    is_nullable: "YES",
    column_default: null,
    character_maximum_length: 64,
    numeric_precision: null,
    numeric_scale: null,
  },
]
`